require('./crud')
require('./hooks')

require('./autoIncrement')
require('./classMethods')
require('./foreignKeys')
require('./includes')
require('./instanceMethods')
require('./primaryKeys')
require('./readOnlyFields')
require('./timestamps')
require('./uniqueKeys')
require('./validation')